export const queryKeys = {
  company: (companyId: string) => ['companies', 'detail', companyId] as const,
  companies: ['companies', 'list'] as const,
  projects: (companyId: string) => ['projects', companyId] as const,
  project: (projectId: string) => ['projects', 'detail', projectId] as const,
  taskGroupsByProject: (projectId: string) => ['taskGroups', 'project', projectId] as const,
  taskGroupsByCompany: (companyId: string) => ['taskGroups', 'company', companyId] as const,
  tasks: (companyId: string) => ['tasks', companyId] as const,
  tasksByFilter: (companyId: string, filter: string) => ['tasks', companyId, filter] as const,
  tasksByCompanies: (companyIds: string[], filter: string) =>
    ['tasks', 'byCompanies', filter, ...companyIds.slice().sort()] as const,
  tasksByProject: (projectId: string) => ['tasks', 'project', projectId] as const,
  completedTasks: (companyId: string) => ['tasks', companyId, 'completed-range'] as const,
  timeEntriesByTask: (taskId: string) => ['timeEntries', 'task', taskId] as const,
  timeEntriesByProject: (projectId: string) => ['timeEntries', 'project', projectId] as const,
  timeEntriesByCompany: (
    companyId: string,
    start: string,
    end: string,
    projectId?: string,
    userId?: string,
  ) => ['timeEntries', 'company', companyId, start, end, projectId ?? null, userId ?? null] as const,
  timeEntriesByCompanies: (
    companyIds: string[],
    start: string,
    end: string,
    projectId?: string,
    userId?: string,
  ) =>
    [
      'timeEntries',
      'byCompanies',
      start,
      end,
      projectId ?? null,
      userId ?? null,
      ...companyIds.slice().sort(),
    ] as const,
  members: (teamId: string) => ['members', teamId] as const,
  reportTasks: (scope: string) => ['reports', scope] as const,
  assignmentsByProject: (projectId: string) => ['assignments', 'project', projectId] as const,
  assignmentsByUser: (userId: string) => ['assignments', 'user', userId] as const,
  discussions: (projectId: string) => ['discussions', projectId] as const,
  discussionsByCompany: (
    companyId: string,
    categoryType: string,
    projectId: string | null,
  ) => ['discussions', 'company', companyId, categoryType, projectId] as const,
  discussionsByCompanies: (
    companyIds: string[],
    categoryType: string,
    projectId: string | null,
  ) =>
    ['discussions', 'byCompanies', categoryType, projectId, ...companyIds.slice().sort()] as const,
  discussion: (discussionId: string) => ['discussions', 'detail', discussionId] as const,
  discussionReplies: (discussionId: string) => ['discussionReplies', discussionId] as const,
  projectFiles: (projectId: string) => ['projectFiles', projectId] as const,
  notifications: (userId: string) => ['notifications', userId] as const,
  userProfiles: ['userProfiles'] as const,
  adminUsers: ['adminUsers'] as const,
  adminUser: (userId: string) => ['adminUsers', userId] as const,
  userProfile: (userId: string) => ['userProfiles', userId] as const,
  developers: ['userProfiles', 'developers'] as const,
  invoices: (companyId?: string, status?: string) =>
    ['invoices', companyId ?? 'all', status ?? 'all'] as const,
  invoice: (invoiceId: string) => ['invoices', 'detail', invoiceId] as const,
};
